os:
  - linux
services:
  - docker
language: node_js
node_js:
  - "8.4.0"
addons:
  apt:
    sources:
    - google-chrome
    packages:
    - google-chrome-stable
cache:
  yarn: true
  directories:
    - node_modules
branches:
  only:
  - master
before_install:
  - export CHROME_BIN=/usr/bin/google-chrome
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
before_script:
- npm install -dev -g @angular/cli@latest
- npm install -g karma
- npm install
- ng build
script:
  - karma start karma.conf.js --single-run
notifications:
  webhooks:
    on_success: change
    on_failure: always
    on_start: false
