dist: trusty
sudo: false

addons:
  chrome: stable

language: node_js

cache:
  directories:
     - ./node_modules

matrix:
  fast_finish: true
  allow_failures:
    - env: nightly
    - env: ng2
    - node_js: "7"
    - node_js: "8"
  include:
    - stage: build
      script: npm run lint
      env: lint
    - script: npm run build
      env: build

    - stage: test
      script: npm run test
      env: test

before_install:
  - npm uninstall -g npm
  # Install npm 5.
  - npm install -g npm@~5.3.0

install:
  - npm install
